ARG CHINA_NODE_IMAGE="m.daocloud.io/docker.io/library/node:22-alpine"
ARG CHINA_NPM_REGISTRY="https://mirrors.cloud.tencent.com/npm/"
ARG CHINA_ALPINE_MIRROR="https://mirrors.aliyun.com/alpine"

# Install dependencies only when needed
FROM ${CHINA_NODE_IMAGE} AS deps
ARG CHINA_NPM_REGISTRY="https://mirrors.cloud.tencent.com/npm/"
ARG CHINA_ALPINE_MIRROR="https://mirrors.aliyun.com/alpine"
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN sed -i "s|https://dl-cdn.alpinelinux.org/alpine|${CHINA_ALPINE_MIRROR}|g" /etc/apk/repositories \
    && apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN export COREPACK_NPM_REGISTRY="${CHINA_NPM_REGISTRY}" \
    && corepack enable \
    && pnpm config set registry "${CHINA_NPM_REGISTRY}" \
    && pnpm install --frozen-lockfile

# Rebuild the source code only when needed
FROM ${CHINA_NODE_IMAGE} AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY docker/middleware.ts ./src

ARG BASE_PATH=/analytics

ENV BASE_PATH=$BASE_PATH
ENV NEXT_TELEMETRY_DISABLED=1
ENV DATABASE_URL="postgresql://user:pass@localhost:5432/dummy"

RUN npm run build-docker

# Production image, copy all the files and run next
FROM ${CHINA_NODE_IMAGE} AS runner
WORKDIR /app

ARG PRISMA_VERSION="6.19.0"
ARG NODE_OPTIONS
ARG CHINA_NPM_REGISTRY="https://mirrors.cloud.tencent.com/npm/"
ARG CHINA_ALPINE_MIRROR="https://mirrors.aliyun.com/alpine"

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_OPTIONS=$NODE_OPTIONS

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN set -x \
    && sed -i "s|https://dl-cdn.alpinelinux.org/alpine|${CHINA_ALPINE_MIRROR}|g" /etc/apk/repositories \
    && apk add --no-cache curl \
    && export COREPACK_NPM_REGISTRY="${CHINA_NPM_REGISTRY}" \
    && corepack enable \
    && pnpm config set registry "${CHINA_NPM_REGISTRY}"

# Script dependencies
RUN pnpm --allow-build='@prisma/engines' add npm-run-all dotenv chalk semver \
    prisma@${PRISMA_VERSION} \
    @prisma/adapter-pg@${PRISMA_VERSION}

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/scripts ./scripts
COPY --from=builder /app/generated ./generated

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV HOSTNAME=0.0.0.0
ENV PORT=3000

CMD ["pnpm", "start-docker"]
